const satori = require('satori').default;
const sharp = require('sharp');
const fs = require('fs');

const fontPath = '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf';
const fontData = fs.readFileSync(fontPath);

const news = [
  { category: 'MACRO', title: 'Trump announces 104% tariffs on China, trade war escalates' },
  { category: 'MACRO', title: 'China retaliates with 84% tariffs on US goods' },
  { category: 'SUPPLY', title: 'TSMC gets $6.6B subsidy for US fab construction' },
  { category: 'SUPPLY', title: 'Samsung Electronics gets $6B chip subsidy' },
  { category: 'CHIP', title: 'Nvidia H20 China-specific chip exposed' },
  { category: 'CHIP', title: 'AMD China layoffs report denied' },
  { category: 'COMPETITOR', title: 'OPPO Find X8 Ultra imaging flagship launched' },
  { category: 'COMPETITOR', title: 'vivo X200s to use Dimensity 9400+ chip' },
  { category: 'OVERSEAS', title: 'Xiaomi Q4 Europe shipments up 35%' },
  { category: 'CONSUMER', title: 'iPhone 16e sales below expectations' },
  { category: 'CONSUMER', title: 'Switch 2 launch event set for April 2' },
];

const leftColumn = news.filter((_, i) => i % 2 === 0);
const rightColumn = news.filter((_, i) => i % 2 === 1);

function newsItem(item) {
  return {
    type: 'div',
    props: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
      marginBottom: '14px',
      padding: '10px',
      backgroundColor: 'rgba(255,255,255,0.5)',
      borderLeft: '3px solid #8B4513',
      borderRadius: '0 6px 6px 0',
      children: [
        { type: 'span', props: { style: { fontSize: '9px', color: '#666', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px' }, children: item.category }},
        { type: 'div', props: { style: { fontSize: '13px', fontWeight: '600', color: '#1a1a1a', lineHeight: '1.35' }, children: item.title }},
      ]
    }
  };
}

const tags = [
  { tag: 'MACRO', color: '#8B0000' },
  { tag: 'SUPPLY', color: '#1E3A5F' },
  { tag: 'CHIP', color: '#2F4F4F' },
  { tag: 'COMPETITOR', color: '#4A3728' },
  { tag: 'OVERSEAS', color: '#006400' },
  { tag: 'CONSUMER', color: '#4A0080' },
];

const jsx = {
  type: 'div',
  props: {
    display: 'flex',
    flexDirection: 'column',
    width: '800px',
    height: '1000px',
    backgroundColor: '#f5f0e6',
    backgroundImage: 'radial-gradient(ellipse at top, #faf8f3 0%, #e8e0d0 100%)',
    padding: '40px',
    children: [
      // Header
      {
        type: 'div',
        props: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          style: { textAlign: 'center', borderBottom: '4px solid #2c1810', paddingBottom: '20px', marginBottom: '30px' },
          children: [
            { type: 'div', props: { style: { fontSize: '52px', fontWeight: '900', color: '#1a0f0a', letterSpacing: '6px' }, children: 'THE DAILY PROPHET' }},
            { type: 'div', props: { style: { fontSize: '14px', color: '#5a4a3a', marginTop: '10px' }, children: 'Daily Tech Briefing · March 31, 2026 · Monday' }},
            { type: 'div', props: { style: { fontSize: '11px', color: '#8a7a6a', marginTop: '4px' }, children: 'Xiaomi Internal · Confidential' }},
          ]
        }
      },
      // Tags
      {
        type: 'div',
        props: {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '10px',
          style: { marginBottom: '24px' },
          children: tags.map(t => ({ type: 'span', props: { style: { padding: '4px 10px', backgroundColor: t.color, color: '#fff', fontSize: '10px', fontWeight: '700', borderRadius: '3px' }, children: t.tag }}))
        }
      },
      // Content columns
      {
        type: 'div',
        props: {
          display: 'flex',
          gap: '30px',
          style: { flex: 1 },
          children: [
            { type: 'div', props: { display: 'flex', flexDirection: 'column', style: { flex: 1 }, children: leftColumn.map(newsItem) }},
            { type: 'div', props: { display: 'flex', flexDirection: 'column', style: { flex: 1 }, children: rightColumn.map(newsItem) }},
          ]
        }
      },
      // Footer
      {
        type: 'div',
        props: {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          style: { marginTop: 'auto', paddingTop: '20px', borderTop: '2px solid #d4c8b0', color: '#8a7a6a', fontSize: '11px' },
          children: 'Generated by pretext-term · Powered by MiniMax-M2.5'
        }
      },
    ],
  },
};

async function generate() {
  console.log('Generating...');
  const svg = await satori(jsx, {
    width: 800,
    height: 1000,
    fonts: [{ name: 'DejaVu Serif', data: fontData, weight: 700, style: 'normal' }],
  });
  await sharp(Buffer.from(svg)).png().toFile('./daily-prophet.png');
  console.log('Done: ./daily-prophet.png');
}
generate().catch(console.error);
