const { toPng } = require('html-to-image');
const fs = require('fs');

const news = [
  { category: 'MACRO', title: 'Trump announces 104% tariffs on China, trade war escalates' },
  { category: 'MACRO', title: 'China retaliates with 84% tariffs on US goods' },
  { category: 'SUPPLY', title: 'TSMC gets $6.6B subsidy for US fab construction' },
  { category: 'SUPPLY', title: 'Samsung Electronics gets $6B chip subsidy' },
  { category: 'CHIP', title: 'Nvidia H20 China-specific chip exposed' },
  { category: 'CHIP', title: 'AMD China layoffs report denied' },
  { category: 'COMPETITOR', title: 'OPPO Find X8 Ultra imaging flagship launched' },
  { category: 'COMPETITOR', title: 'vivo X200s to use Dimensity 9400+ chip' },
  { category: 'OVERSEAS', title: 'Xiaomi Q4 Europe shipments up 35%' },
  { category: 'CONSUMER', title: 'iPhone 16e sales below expectations' },
  { category: 'CONSUMER', title: 'Switch 2 launch event set for April 2' },
];

const leftColumn = news.filter((_, i) => i % 2 === 0);
const rightColumn = news.filter((_, i) => i % 2 === 1);

const tags = [
  { tag: 'MACRO', color: '#8B0000' },
  { tag: 'SUPPLY', color: '#1E3A5F' },
  { tag: 'CHIP', color: '#2F4F4F' },
  { tag: 'COMPETITOR', color: '#4A3728' },
  { tag: 'OVERSEAS', color: '#006400' },
  { tag: 'CONSUMER', color: '#4A0080' },
];

function newsItem(item) {
  return `
    <div style="display: flex; flex-direction: column; gap: 4px; margin-bottom: 14px; padding: 10px; background: rgba(255,255,255,0.5); border-left: 3px solid #8B4513; border-radius: 0 6px 6px 0;">
      <span style="font-size: 9px; color: #666; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">${item.category}</span>
      <div style="font-size: 13px; font-weight: 600; color: #1a1a1a; line-height: 1.35;">${item.title}</div>
    </div>
  `;
}

const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Serif:wght@400;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: 'Noto Serif', Georgia, serif;
      background: radial-gradient(ellipse at top, #faf8f3 0%, #e8e0d0 100%);
      width: 800px; height: 1000px; padding: 40px;
      display: flex; flex-direction: column;
    }
    .header { 
      text-align: center; border-bottom: 4px solid #2c1810; padding-bottom: 20px; margin-bottom: 30px; 
    }
    .header h1 { font-size: 52px; font-weight: 900; color: #1a0f0a; letter-spacing: 6px; }
    .header .date { font-size: 14px; color: #5a4a3a; margin-top: 10px; }
    .header .conf { font-size: 11px; color: #8a7a6a; margin-top: 4px; }
    .tags { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 24px; }
    .tag { padding: 4px 10px; color: #fff; font-size: 10px; font-weight: 700; border-radius: 3px; }
    .content { display: flex; gap: 30px; flex: 1; }
    .column { flex: 1; display: flex; flex-direction: column; }
    .footer { margin-top: auto; padding-top: 20px; border-top: 2px solid #d4c8b0; text-align: center; color: #8a7a6a; font-size: 11px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>THE DAILY PROPHET</h1>
    <div class="date">Daily Tech Briefing · March 31, 2026 · Monday</div>
    <div class="conf">Xiaomi Internal · Confidential</div>
  </div>
  <div class="tags">
    ${tags.map(t => `<span class="tag" style="background: ${t.color}">${t.tag}</span>`).join('')}
  </div>
  <div class="content">
    <div class="column">
      ${leftColumn.map(newsItem).join('')}
    </div>
    <div class="column">
      ${rightColumn.map(newsItem).join('')}
    </div>
  </div>
  <div class="footer">Generated by pretext-term · Powered by MiniMax-M2.5</div>
</body>
</html>
`;

// Write HTML to file
fs.writeFileSync('./daily-prophet.html', html);
console.log('HTML written to daily-prophet.html');

// Create a simple node script that uses jsdom + canvas to render
// Actually, html-to-image needs a DOM environment. Let's use a different approach.
